name: dinissa
description: "Peer-to-peer crypto exchange and fintech app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  animated_splash_screen: ^1.3.0
  curved_navigation_bar: ^1.0.3
  flutter_lints: ^3.0.0
  fl_chart: ^0.69.0
  gap: ^3.0.1
  http: ^1.2.1
  crypto: ^3.0.1
  persistent_bottom_nav_bar: ^6.2.1
  dot_curved_bottom_nav: ^0.0.1
  page_transition: ^2.1.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.5.0
  firebase_storage: ^11.4.0
  card_swiper: ^3.0.0
  dio: ^5.5.0+1
  get: ^4.6.6
  shared_preferences: ^2.3.1
  get_storage: ^2.0.1

  collection: any
  pinput: ^5.0.0
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.0
  sidebarx: ^0.17.1
  loading_animation_widget: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  oauth2: ^2.0.3
  internet_connection_checker: ^1.0.0+1
  qr_flutter: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^2.4.0
  # animated_splash_screen: ^1.3.0
  # curved_navigation_bar: ^1.0.3
  # flutter_lints: ^3.0.0
  # fl_chart: ^0.36.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # Uncomment and customize the following lines to add custom fonts:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita-Bold.otf
          weight: 700
        - asset: assets/fonts/Gordita-Medium.otf
          weight: 600
        - asset: assets/fonts/Gordita-Regular.otf
          weight: 500
