name: dinissa
description: "Peer-to-peer crypto exchange and fintech app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  animated_splash_screen: ^1.3.0
  curved_navigation_bar: ^1.0.3
  flutter_lints: ^3.0.0
  fl_chart: ^0.36.0
  http: ^1.2.1
  crypto: ^3.0.1
  persistent_bottom_nav_bar: ^6.2.1
  dot_curved_bottom_nav: ^0.0.1
  page_transition: ^2.1.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^2.4.0
  # animated_splash_screen: ^1.3.0
  # curved_navigation_bar: ^1.0.3
  # flutter_lints: ^3.0.0
  # fl_chart: ^0.36.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/team.svg
    - assets/images/investor.svg
    - assets/images/savings.svg
    - assets/images/success.svg
    - assets/images/Sun.png
    - assets/images/undraw_walking_in_rain_vo9p 2.png
    - assets/images/profile.png

  # Uncomment and customize the following lines to add custom fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
